apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-data
  namespace: infrastructure
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
