apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - postgres-bootstrap-job.yaml
  - postgres-tailscale-service.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - backup-cronjob.yaml
  - lira-sync-cronjob.yaml
