apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
  namespace: jellyfin

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jellyfin
  name: tailscale
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["tailscale-state"]
  verbs: ["get", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: jellyfin
subjects:
- kind: ServiceAccount
  name: tailscale
  namespace: jellyfin
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
