apiVersion: v1
kind: ConfigMap
metadata:
  name: jellyfin-serve-config
  namespace: jellyfin
data:
  serve.json: |
    {
      "TCP": {
        "443": {
          "HTTPS": true
        }
      },
      "Web": {
        "jellyfin.twin-barley.ts.net:443": {
          "Handlers": {
            "/": {
              "Proxy": "http://127.0.0.1:8096"
            }
          }
        }
      }
    }
