apiVersion: apps/v1
kind: Deployment
metadata:
  name: restate
  namespace: restate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restate
  template:
    metadata:
      labels:
        app: restate
    spec:
      serviceAccountName: tailscale
      containers:
      - name: restate
        image: restatedev/restate:latest
        ports:
        - containerPort: 9070  # Admin/UI port
        - containerPort: 8080  # Ingress port for services
        - containerPort: 9071  # Metrics port
        env:
        - name: RESTATE_CONFIG_FILE
          value: /config/restate.toml
        - name: RUST_LOG
          value: info,restate=debug
        volumeMounts:
        - name: restate-data
          mountPath: /data
        - name: restate-config
          mountPath: /config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 9070
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 9070
          initialDelaySeconds: 10
          periodSeconds: 10
      - name: tailscale
        image: tailscale/tailscale:latest
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
        - name: TS_HOSTNAME
          value: "restate"
        - name: TS_SERVE_CONFIG
          value: "/config/serve.json"
        - name: TS_STATE_DIR
          value: /tmp
        - name: TS_USERSPACE
          value: "true"
        - name: TS_KUBE_SECRET
          value: "tailscale-state"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - name: serve-config
          mountPath: /config
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: restate-data
        hostPath:
          path: /mnt/primary/k3s-storage/restate-data
          type: DirectoryOrCreate
      - name: serve-config
        configMap:
          name: tailscale-serve-config
      - name: restate-config
        configMap:
          name: restate-config
