apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - rbac.yaml
  - serve-config.yaml
  - restate-config.yaml
  - deployment.yaml
  - service.yaml
