apiVersion: v1
kind: Service
metadata:
  name: restate
  namespace: restate
spec:
  selector:
    app: restate
  ports:
  - name: admin
    port: 9070
    targetPort: 9070
  - name: ingress
    port: 8080
    targetPort: 8080
  - name: metrics
    port: 9071
    targetPort: 9071
---
# Optional: NodePort for direct local access during development
apiVersion: v1
kind: Service
metadata:
  name: restate-dev
  namespace: restate
spec:
  type: NodePort
  selector:
    app: restate
  ports:
  - name: admin
    port: 9070
    targetPort: 9070
    nodePort: 30070
  - name: ingress
    port: 8080
    targetPort: 8080
    nodePort: 30080