apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      serviceAccountName: tailscale
      initContainers:
      # Ensure basic directory structure exists with proper permissions
      - name: init-dirs
        image: busybox
        command: ['sh', '-c']
        args:
        - |
          # Only create the base directories, let Nextcloud create user-specific ones
          mkdir -p /userdata/photos
          mkdir -p /userdata/media
          chown -R 33:33 /userdata
          # Don't create admin/ or admin/files/ - let Nextcloud do that
        volumeMounts:
        - name: nextcloud-userdata
          mountPath: /userdata
      containers:
      - name: nextcloud
        image: nextcloud:28-apache
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_DB
          value: nextcloud
        - name: POSTGRES_USER
          value: nextcloud
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: POSTGRES_PASSWORD
        - name: NEXTCLOUD_ADMIN_USER
          value: admin
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: NEXTCLOUD_ADMIN_PASSWORD
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: "nextcloud.twin-barley.ts.net localhost"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nextcloud-data
          mountPath: /var/www/html
        - name: nextcloud-userdata
          mountPath: /var/www/html/data
        resources:
          requests:
            memory: 2Gi
            cpu: 250m
          limits:
            memory: 4Gi
            cpu: 1000m
        readinessProbe:
          httpGet:
            path: /status.php
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
      - name: tailscale
        image: tailscale/tailscale:latest
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
        - name: TS_HOSTNAME
          value: "nextcloud"
        - name: TS_SERVE_CONFIG
          value: "/config/serve.json"
        - name: TS_STATE_DIR
          value: /tmp
        - name: TS_USERSPACE
          value: "true"
        - name: TS_KUBE_SECRET
          value: "tailscale-state"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - name: serve-config
          mountPath: /config
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 100m
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
      volumes:
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-data
      - name: nextcloud-userdata
        hostPath:
          path: /mnt/primary/k3s-storage/nextcloud-userdata
          type: DirectoryOrCreate
      - name: serve-config
        configMap:
          name: tailscale-serve-config
