apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: nextcloud
        - name: POSTGRES_USER
          value: nextcloud
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        # Enable detailed logging
        - name: POSTGRES_INITDB_ARGS
          value: "--auth-host=md5"
        command: ["docker-entrypoint.sh"]
        args:
        - "postgres"
        - "-c"
        - "log_statement=all"
        - "-c" 
        - "log_connections=on"
        - "-c"
        - "log_disconnections=on"
        - "-c"
        - "log_line_prefix=%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h "
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: postgres-init
          mountPath: /docker-entrypoint-initdb.d/
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 500m
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: nextcloud-postgres
      - name: postgres-init
        configMap:
          name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: nextcloud
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
