apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-primary
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-postgres
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-primary
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-userdata
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-primary
  resources:
    requests:
      storage: 1Ti
