apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      containers:
      - name: samba
        image: dperson/samba:latest
        env:
        - name: USERID
          value: "33"  # www-data user ID (same as Nextcloud)
        - name: GROUPID
          value: "33"  # www-data group ID
        - name: SMB_USER
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: SMB_USER
        - name: SMB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: SMB_PASSWORD
        command: ["/bin/bash"]
        args:
        - "-c"
        - |
          /usr/bin/samba.sh \
            -u "${SMB_USER};${SMB_PASSWORD}" \
            -s "nextcloud;/data;yes;no;no;${SMB_USER};${SMB_USER};${SMB_USER}" \
            -s "photos;/data/photos;yes;no;no;${SMB_USER};${SMB_USER};${SMB_USER}" \
            -s "media;/data/media;yes;no;no;${SMB_USER};${SMB_USER};${SMB_USER}"
        ports:
        - containerPort: 139
        - containerPort: 445
        volumeMounts:
        - name: nextcloud-userdata
          mountPath: /data
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 200m
        securityContext:
          privileged: true  # Required for SMB
      volumes:
      - name: nextcloud-userdata
        hostPath:
          path: /mnt/primary/k3s-storage/nextcloud-userdata
          type: DirectoryOrCreate
---
# SMB services - both NodePort for LAN access
apiVersion: v1
kind: Service
metadata:
  name: samba-netbios
  namespace: nextcloud
spec:
  type: NodePort
  selector:
    app: samba
  ports:
  - name: netbios
    port: 139
    targetPort: 139
    nodePort: 30139
---
apiVersion: v1
kind: Service
metadata:
  name: samba-smb
  namespace: nextcloud
spec:
  type: NodePort
  selector:
    app: samba
  ports:
  - name: smb
    port: 445
    targetPort: 445
    nodePort: 30445
