apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
  namespace: immich
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: immich
  name: tailscale
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: immich
subjects:
- kind: ServiceAccount
  name: tailscale
  namespace: immich
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io