apiVersion: apps/v1
kind: Deployment
metadata:
  name: copyparty
  namespace: copyparty
  labels:
    app: copyparty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: copyparty
  template:
    metadata:
      labels:
        app: copyparty
    spec:
      serviceAccountName: tailscale
      containers:
      - name: copyparty
        image: copyparty/ac:latest
        args:
        - "-a"
        - "andrew:$(COPYPARTY_PASSWORD)"
        - "--log-badxml"
        ports:
        - containerPort: 3923
          name: http
        volumeMounts:
        - name: files
          mountPath: /w
        - name: audiobooks
          mountPath: /audiobooks
        - name: config
          mountPath: /cfg
        - name: copyparty-config
          mountPath: /cfg/config.conf
          subPath: config.conf
          readOnly: true
        env:
        # User password from secret
        - name: COPYPARTY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: copyparty-secrets
              key: password
        # Optional performance enhancement
        - name: LD_PRELOAD
          value: "/usr/lib/libmimalloc-secure.so.2"
        resources:
          requests:
            memory: "1Gi"
            cpu: "200m"
          limits:
            memory: "3Gi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /
            port: 3923
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3923
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
      
      # Tailscale sidecar for secure remote access
      - name: tailscale
        image: tailscale/tailscale:latest
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
        - name: TS_HOSTNAME
          value: "copyparty"
        - name: TS_SERVE_CONFIG
          value: "/config/serve.json"
        - name: TS_STATE_DIR
          value: /tmp
        - name: TS_USERSPACE
          value: "true"
        - name: TS_KUBE_SECRET
          value: "tailscale-state"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - name: serve-config
          mountPath: /config
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000

      volumes:
      - name: files
        hostPath:
          path: /mnt/primary/k3s-storage/files
          type: Directory
      - name: audiobooks
        hostPath:
          path: /mnt/primary/k3s-storage/audiobooks
          type: Directory
      - name: config
        hostPath:
          path: /mnt/primary/k3s-storage/copyparty-config
          type: Directory
      - name: copyparty-config
        configMap:
          name: copyparty-config
      - name: serve-config
        configMap:
          name: tailscale-serve-config
