apiVersion: apps/v1
kind: Deployment
metadata:
  name: maybe
  namespace: maybe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maybe
  template:
    metadata:
      labels:
        app: maybe
    spec:
      serviceAccountName: tailscale
      initContainers:
      - name: wait-for-postgres
        image: postgres:16
        command: ['sh', '-c']
        args:
        - |
          until pg_isready -h postgres -p 5432 -U maybe_user; do
            echo "Waiting for postgres..."
            sleep 2
          done
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: maybe-secrets
              key: POSTGRES_PASSWORD
      containers:
      - name: maybe-web
        image: ghcr.io/maybe-finance/maybe:sha-9110ab27d26536a8385f467f183168075b5ec3f6
        ports:
        - containerPort: 3000
        env:
        - name: SELF_HOSTING_ENABLED
          value: "true"
        - name: RAILS_FORCE_SSL
          value: "false"
        - name: RAILS_ASSUME_SSL
          value: "false"
        - name: GOOD_JOB_EXECUTION_MODE
          value: "async"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: maybe-secrets
              key: SECRET_KEY_BASE
        - name: DB_HOST
          value: "postgres"
        - name: POSTGRES_DB
          value: "maybe_production"
        - name: POSTGRES_USER
          value: "maybe_user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: maybe-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_URL
          value: "redis://redis:6379"
        volumeMounts:
        - name: app-storage
          mountPath: /rails/storage
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /up
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /up
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      - name: maybe-worker
        image: ghcr.io/maybe-finance/maybe:sha-9110ab27d26536a8385f467f183168075b5ec3f6
        command: ["bundle", "exec", "sidekiq"]
        env:
        - name: SELF_HOSTING_ENABLED
          value: "true"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: maybe-secrets
              key: SECRET_KEY_BASE
        - name: DB_HOST
          value: "postgres"
        - name: POSTGRES_DB
          value: "maybe_production"
        - name: POSTGRES_USER
          value: "maybe_user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: maybe-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_URL
          value: "redis://redis:6379"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      - name: tailscale
        image: tailscale/tailscale:latest
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
        - name: TS_HOSTNAME
          value: "maybe"
        - name: TS_SERVE_CONFIG
          value: "/config/serve.json"
        - name: TS_STATE_DIR
          value: "/tmp"
        - name: TS_USERSPACE
          value: "true"
        - name: TS_KUBE_SECRET
          value: "tailscale-state"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - name: serve-config
          mountPath: /config
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: maybe-app-storage
      - name: serve-config
        configMap:
          name: tailscale-serve-config
