apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - pvc.yaml
  - secrets.yaml
  - serve-config.yaml
  - redis.yaml
  - postgres.yaml
  - deployment.yaml
