apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: maybe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: POSTGRES_USER
          value: "maybe_user"
        - name: POSTGRES_DB
          value: "maybe_production"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: maybe-secrets
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - maybe_user
            - -d
            - maybe_production
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - maybe_user
            - -d
            - maybe_production
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: maybe-postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: maybe
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
