apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkwarden
  namespace: linkwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkwarden
  template:
    metadata:
      labels:
        app: linkwarden
    spec:
      serviceAccountName: tailscale
      initContainers:
      - name: wait-for-postgres
        image: postgres:16
        command: ['sh', '-c']
        args:
        - |
          until pg_isready -h postgres -p 5432 -U linkwarden_user; do
            echo "Waiting for postgres..."
            sleep 2
          done
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: linkwarden-secrets
              key: POSTGRES_PASSWORD
      containers:
      - name: linkwarden
        image: ghcr.io/linkwarden/linkwarden:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: linkwarden-secrets
              key: NEXTAUTH_SECRET
        - name: NEXTAUTH_URL
          value: "https://linkwarden.twin-barley.ts.net/api/v1/auth"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: linkwarden-secrets
              key: DATABASE_URL
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: linkwarden-secrets
              key: POSTGRES_PASSWORD
        - name: MEILI_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: linkwarden-secrets
              key: MEILI_MASTER_KEY
        volumeMounts:
        - name: app-data
          mountPath: /data/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      - name: tailscale
        image: tailscale/tailscale:latest
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
        - name: TS_HOSTNAME
          value: "linkwarden"
        - name: TS_SERVE_CONFIG
          value: "/config/serve.json"
        - name: TS_STATE_DIR
          value: "/tmp"
        - name: TS_USERSPACE
          value: "true"
        - name: TS_KUBE_SECRET
          value: "tailscale-state"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - name: serve-config
          mountPath: /config
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: app-data
        hostPath:
          path: /mnt/primary/k3s-storage/linkwarden-data
          type: DirectoryOrCreate
      - name: serve-config
        configMap:
          name: tailscale-serve-config
