apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: linkwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: POSTGRES_USER
          value: "linkwarden_user"
        - name: POSTGRES_DB
          value: "linkwarden"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: linkwarden-secrets
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - linkwarden_user
            - -d
            - linkwarden
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - linkwarden_user
            - -d
            - linkwarden
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-data
        hostPath:
          path: /mnt/primary/k3s-storage/linkwarden-postgres
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: linkwarden
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432