apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- secrets.yaml
- rbac.yaml
- pvc.yaml
- serve-config.yaml
- config.yaml
- datasource.yaml
- service.yaml
- deployment.yaml
