apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-primary
  resources:
    requests:
      storage: 10Gi