apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
  namespace: freshrss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      serviceAccountName: tailscale
      containers:
      - name: freshrss
        image: freshrss/freshrss:latest
        ports:
        - containerPort: 80
        env:
        - name: CRON_MIN
          value: "1,31"
        volumeMounts:
        - name: data
          mountPath: /var/www/FreshRSS/data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      - name: tailscale
        image: tailscale/tailscale:latest
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
        - name: TS_HOSTNAME
          value: "freshrss"
        - name: TS_SERVE_CONFIG
          value: "/config/serve.json"
        - name: TS_STATE_DIR
          value: /tmp
        - name: TS_USERSPACE
          value: "true"
        - name: TS_KUBE_SECRET
          value: "tailscale-state"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - name: serve-config
          mountPath: /config
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: data
        hostPath:
          path: /mnt/primary/k3s-storage/freshrss-data
          type: DirectoryOrCreate
      - name: serve-config
        configMap:
          name: tailscale-serve-config
