apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freshrss
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: freshrss.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: freshrss
            port:
              number: 80
