apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data
  namespace: freshrss
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-primary
  resources:
    requests:
      storage: 5Gi
