apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
  namespace: freshrss
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
  namespace: freshrss
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: freshrss
subjects:
- kind: ServiceAccount
  name: tailscale
  namespace: freshrss
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
